export const GRAPH_SAFE_ZONE = 25;
export const GRAPH_RENDER_INTERVAL = 25;
export const GRAPH_K_CONSTANT = 0.001 * GRAPH_RENDER_INTERVAL;
export const GRAPH_AMORTIZATION_FACTOR = 0.005 * (GRAPH_RENDER_INTERVAL + 10);

export const GRAPH_TRANSITION_SPEED = 1 / 4;
